server:
  port: 8081
  servlet:
    context-path: /api
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/departmentservice
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true