server:
  port: 8082
  servlet:
    context-path: /api
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost/userservice
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql